OCSP example
payara/Payara-Examples pull request #136
Opened 2021-07-11 10:08 UTC by rdebusscher

Requires https://github.com/payara/Payara-Examples/pull/135 (as example is using ClientCertificateValidator of 5.2021.5)

2021-08-17 14:24 UTC, OndroMih approved these changes

2021-08-17 17:58 UTC, rdebusscher commented
ClientCertificateValidator is not yet available in master due issues.  Keep this ON HOLD!!

2021-09-16 16:19 UTC, OndroMih requested changes
The version in the parent pom must be the latest version 5.2021.7, otherwise this doesn't compile.

2021-09-16 16:31 UTC, OndroMih requested changes
Also the API package changed in the final version

2021-09-16 16:31 UTC, OndroMih commented on security/client-certificate-validator/src/main/java/fish/payara/example/security/certificate/MyValidator.java
> +import fish.payara.security.api.ClientCertificateValidator;
```suggestion
import fish.payara.security.client.ClientCertificateValidator;
```
The package changed in the final API artifact.

2021-09-16 16:31 UTC, OndroMih commented on security/client-certificate-validator/src/main/resources/META-INF/services/fish.payara.security.api.ClientCertificateValidator
> +fish.payara.example.security.certificate.MyValidator
This file needs to be renamed to `fish.payara.security.client.ClientCertificateValidator` because the package changed.

2021-09-16 19:09 UTC, rdebusscher commented
Correct, OCSP example was created for first version of the Client Certificate Validator that was never merged.  Updated.

2021-09-17 12:44 UTC, OndroMih commented on security/client-certificate-validator/src/main/resources/META-INF/services/fish.payara.security.api.ClientCertificateValidator
> +fish.payara.example.security.certificate.MyValidator
Hi @rdebusscher, please also see this. This file needs to be renamed too to match the new package name.

2021-09-17 13:48 UTC, OndroMih approved these changes

2021-09-17 13:48 UTC, merged